applications:
  app:
    type: php:8.3

    relationships:
      database: "db:mysql"

    build:
      flavor: composer

    web:
      locations:
        "/":
          root: "public"
          passthru: "/index.php"
          index:
            - index.php

    hooks:
      build: |
        set -e
        composer install --no-dev --optimize-autoloader

services:
  db:
    type: mariadb:10.6

routes:
  "https://{default}/":
    type: upstream
    upstream: "app:http"